# Generated by Django 5.2.3 on 2025-09-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminuser_alter_candidate_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='unique_code',
            field=models.CharField(max_length=50),
        ),
    ]
