# Generated by Django 5.2.3 on 2025-10-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_votingtime_alter_voter_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.adminuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, default='Independent', max_length=100),
            preserve_default=False,
        ),
    ]
